apiVersion: batch/v1
kind: CronJob
metadata:
  name: traefik-allowlist-sync
spec:
  schedule: "*/5 * * * *"
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: traefik
          containers:
            - name: traefik-allowlist-sync
              image: kubitodev/traefik-ip-allowlist-sync:latest
              env:
                - name: ALLOWLIST_MIDDLEWARE_NAME
                  value: ip-allowlist
                - name: ALLOWLIST_TRAEFIK_NAMESPACE
                  value: traefik-system
                # - name: ALLOWLIST_CUSTOM_DOMAIN
                #   value: example.com
          restartPolicy: OnFailure
