apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: ip-allowlist
spec:
  ipAllowList:
    sourceRange:
      - 1.1.1.1 # dynamically changing
    # Uncomment if you need to set depth
    # ipStrategy:
    #   depth: 1
    #   excludedIPs: []
